baseURL: https://martin-doumanov-portfolio.netlify.app/
languageCode: en-us
title: Portfolio website for Martin Doumanov
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Explore
    subtitle: Welcome to my Portfolio Website for Data Analytics in Finance
    title: Welcome to Martin's Protfolio
  blog: {}
  contact:
    address:
      - city: London, NW6 5UA
        country: UK
        street: Kilburn High Road
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: mdoumanov.mfa2022@london.edu
        title: Email
   # enable: yes
    #phone:
     # - phone: (000) 000-0000 x1234
      #  title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Martin Doumanov
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
     # - icon: fa-twitter
      #  label: Twitter
      #  url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/mdoumanov/
    #  - icon: fa-instagram
     #   label: Instagram
      #  url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/martin-doumanov
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/mdoumanov/
  image: ''
  name: Martin Doumanov
  navigation:
    button1:
      - name: Explore
        url: blogs
    #button2:
     # - name: Log In
      #  url: '#'
    links:
      - name: Home
        url: '#'
      - name: About Me
        url: blogs/about_me
      - name: Blogs
        url: blogs
      #- name: Elements
        #url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpg
        subtitle: MFA '22 | NYUAD '21 | ACS '17
        title: About Me
        url: blogs/about_me
      - image: louvre.jpg
        subtitle: A young professional with experiences in IB, VC, and Consulting
        title: Resume
        url: blogs/resume
      - image: sky.jpg
        subtitle: Some of my favorite work
        title: Photography
        url: blogs/photography
      - image: work.jpg
        subtitle: A collection of my best visualisations
        title: Visualisations
        url: blogs/visuals
      - image: pic05.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Consequat
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: Go back?
    enable: yes
    subtitle: "You have just visited my final project for Data Analytics for Finance. 
    \r\n I hope you have learned more about me and you found something that peeked your interest. Come again!"
    title: Thank you for coming!
    url: blogs
